---
- name: example playbook
  hosts: localhost

  tasks:
    - name: Ensure a line is present in a file
      lineinfile:
        path: /home/kshitij/2x2_tic_tac_toe.pm
        line: 'Your desired line here'
        owner: kshitij
        group: kshitij
        mod: "0644"
        

    - name: Ensure a line is present in a file
      lineinfile:
        path: /home/kshitij/2x2_tic_tac_toe.pm
        line: 'Your desired line here'
        state: present


    - name: Create a group
      group:
        name: yourgroup
        state: present  
      
    - name: Create a user
      user:
        name: yourusername
        password: yourpassword  
        groups: yourgroup    
        state: present       
        shell: /bin/bash     
      
