FROM registry.access.redhat.com/ubi8/ubi

# Install SSH server
RUN dnf install -y openssh-server && dnf clean all
RUN useradd -m -d /home/redhat -s /bin/bash -g root -G wheel -u 1000 test

# Configure SSH
RUN ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N '' && ssh-keygen -t ecdsa -f /etc/ssh/ssh_host_ecdsa_key -N '' && ssh-keygen -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -N ''
RUN echo 'root:password' | chpasswd
RUN echo -e "PasswordAuthentication no\nPubkeyAuthentication yes\nPermitRootLogin yes" >> /etc/ssh/sshd_config

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]
